#!/usr/bin/env python3
import sys
from color import ColorMsg
from menu import MainMenu, WalletMenu
from notary import Notary
from configure import Config

color_msg = ColorMsg()
menu = MainMenu()
wallet_menu = WalletMenu()
notary = Notary()
cfg = Config()

print('''
  ________                                         _____   __     _________      
  ___  __ `____________ _ _____ _____________      ___/ | / /___________/ /____  
  __  / / /_/ ___// __ `/ / __ ` / __ `_/ __ `     __/  |/ / / __ `/ __  / / _ ` 
  _  /_/ /_/ /   / /_/ / / /_/ // /_/ // / / /     _/ /|  / / /_/ / /_/ / /  __/ 
  /_____/ /_/    `__,_/  `__, / `____//_/ /_/      /_/ |_/  `____/`__,_/  `___/  
                        /____/                                                   
''' + '{:^80}'.format('Dragon Node menu v0.2 by Dragonhound'))
print()
if notary.configured:
    notary.welcome()


menu.show()