#!/usr/bin/env python3
from menu import MainMenu
from notary import Notary

menu = MainMenu()
notary = Notary()

print('''
  ________                                         _____   __     _________      
  ___  __ `____________ _ _____ _____________      ___/ | / /___________/ /____  
  __  / / /_/ ___// __ `/ / __ ` / __ `_/ __ `     __/  |/ / / __ `/ __  / / _ ` 
  _  /_/ /_/ /   / /_/ / / /_/ // /_/ // / / /     _/ /|  / / /_/ / /_/ / /  __/ 
  /_____/ /_/    `__,_/  `__, / `____//_/ /_/      /_/ |_/  `____/`__,_/  `___/  
                        /____/                                                   
''' + '{:^80}'.format('Dragon Node menu v0.2 by Dragonhound'))
print()
if notary.configured:
    notary.welcome()

menu.show()
