#!/usr/bin/env python3
from menu import MainMenu
from notary import Notary
from color import ColorMsg

menu = MainMenu()
notary = Notary()
msg = ColorMsg()

msg.table('''
  ________                                         _____   __     _________      
  ___  __ `____________ _ _____ _____________      ___/ | / /___________/ /____  
  __  / / /_/ ___// __ `/ / __ ` / __ `_/ __ `     __/  |/ / / __ `/ __  / / _ ` 
  _  /_/ /_/ /   / /_/ / / /_/ // /_/ // / / /     _/ /|  / / /_/ / /_/ / /  __/ 
  /_____/ /_/    `__,_/  `__, / `____//_/ /_/      /_/ |_/  `____/`__,_/  `___/  
                        /____/                                                   
''')
msg.ltcyan('{:^80}'.format('Dragon Node menu v0.2 by Dragonhound'))
print()
notary.welcome()
menu.show()
